### ISSUE TITLE
Question about --snapshotMode

### ISSUE THREAD

**Issue by raijinsetsu** [GoogleContainerTools/kaniko#1057]
### Background
We use a Jenkins multi-branch pipeline job to submit builds to Cloud Build. This means that the timestamps on the files will be as of the latest "git checkout" invocation and, therefore, will be different for each branch (Jenkins checks each branch out into it's own working copy).

### Question
It's implied, but not explicit, that "--snapshotMode=full" uses both the modified time and "something else", probably the hash of the file, to determine a hash for the file. As the time is included, this means that layers will never be cached between branches because the timestamps will be different. Is this true?

If it is, would the developers be amenable to "--snapshotMode=hash" or, even better for those of us using Git, "--snapshotMode=git-commit" (using the commit hash from when the file was last modified)?

**Comment by tejal29** [comment]
@raijinsetsu Thank you for your patience. 

Regarding your question, 

>It's implied, but not explicit, that "--snapshotMode=full" uses both the modified time and "something else", probably the hash of the file, to determine a hash for the file.

Yes `--snapshotMode-=full` which is the default mode for snapshotting uses both the modified time and hash of the file contents like you suspected to see if a file has changed. the code is [here](https://github.com/GoogleContainerTools/kaniko/blob/master/pkg/util/util.go#L36) 

>As the time is included, this means that layers will never be cached between branches because the timestamps will be different. Is this true? 

The `--snapshotMode` is *only* used to determine if the file changes between two layer. 
However, for caching purposes Kaniko uses `CacheHasher` which does not include mTime hasher at all 
See 
https://github.com/GoogleContainerTools/kaniko/blob/0fe0a64113fb9755f6896a805f67dbfdb02acf0d/pkg/snapshot/layered_map.go#L36-L37

The reason, we dont want to support `snapshotMode=hash` is because a file permission, group etc changes should be detected. 
The [`CacheHasher`](https://github.com/GoogleContainerTools/kaniko/blob/master/pkg/util/util.go#L76) takes in to account not just contents like the full mode cacher but the permission on the file too. 

Regarding an enhancement for `--snapshotMode=git-commit` it would help speed up performance all files in the workdir which belong to a git repo. However, kaniko still needs to determine if other files in the workdir changed due to a `Run` or any other command. 
It would a be a good idea to benchmark this performance gain. I am guessing for huge repositories this could be substantial. 
Would you be up for exploring something like this?

**Comment by raijinsetsu** [comment]
Thanks Tejal!
