### ISSUE TITLE
Why are `COPY` layers cacheable?

### ISSUE THREAD

**Issue by isker** [GoogleContainerTools/kaniko#1357]
The [README says](https://github.com/GoogleContainerTools/kaniko/blob/0c71a1bb0ea1eb619ea369a72cd0d6763790aa3f/README.md#caching-layers) that only `RUN` layers are cacheable.  But last year `COPY`s were also made cacheable 
 in https://github.com/GoogleContainerTools/kaniko/commit/dbabcb1f5fc101c2735c9438cf326e8a8a51aac4 (cc @donmccasland).

I'm not an expert in docker, but it's not clear at face value why you'd want to cache such layers.  If you're `COPY`ing some data in, you already have it locally, right?  But when layer caching is enabled with a remote repository, instead of just executing that local copy, you hash that local data, then go to the network to download a layer containing the same data.  Or, upon a miss, you spend time pushing the layer to your cache.

We have a performance-sensitive image build using Kaniko that has a few `RUN`s that we'd like cached, and some large `COPY`s that, being cached, are actually offsetting performance improvements from caching `RUN`s.  And our image cache is much larger than we'd like.

@donmccasland can you clarify the intent of cacheable `COPY`s?  And would you be receptive to a PR adding a flag to disable caching for `COPY` commands?

Thanks for your time!

**Comment by kamaln7** [comment]
My guess is that this was added for non disk-local contexts like S3 & friends. If that is the case maybe disabling COPY caching when the context is a `dir://` or `tar://`

**Comment by isker** [comment]
As far as I can tell from reading [the docs](https://docs.docker.com/engine/reference/builder/#copy), you can only COPY things that are already in the local docker build context.

Even if they could be remote, you'd still have to hash them in order to check the layer cache.  And to hash them you'd presumably have to download them locally first.

**Comment by isker** [comment]
@donmccasland sorry to ping you again, but if you can provide any guidance here I'd appreciate it!  If there's anything to do I'm more than happy to implement.

**Comment by tejal29** [comment]
@isker Sorry for the delay. @donmccasland is no longer actively working on this project.

Reason why copy layers are cacheable is to determine if the subsequent  run commands can be used from cache.
e.g.
in order to determine if the subsequent `Run` command can be used from cached layer, kaniko computes if `package.json` has changed. if it has changed, then cache layer for `Run yarn install` is invalidated.
If not, then we use the cache layer for `Run` command.
```
Copy package.json . 
Run yarn install
```

The way kaniko caching works is, it uses the cache until a cache key for one command in dockerfile is changed.
once it detects a change, it stops using cache for subsequent run commands.

I would suggest, you could re-arrange your dockerfile so that file copies not affecting run command should come later.
Doed that make sense?

**Comment by isker** [comment]
@tejal29 Thanks for responding.

> The way kaniko caching works is, it uses the cache until a cache key for one command in dockerfile is changed.
once it detects a change, it stops using cache for subsequent run commands.

This is what I did not understand.  Unfortunately our Dockerfile is fundamentally copy-heavy.  The ordering of COPYs and RUNs is already optimal in this regard.

If you'll entertain more questions, why does Kaniko's layer cache work that way?  Why can't it go back to the cache after producing a layer locally?

I will open a PR documenting this behavior in the README.

**Comment by kamaln7** [comment]
Thanks for the explanation @tejal29 that makes sense!

I'm trying to follow [the caching logic here](https://github.com/GoogleContainerTools/kaniko/blob/0c7e1644cb8b4fe597cf89caf179ef603fc43c7a/pkg/executor/build.go#L218) and I'm probably missing something obvious, but would something like this work?

With COPY commands specifically, instead of:

1. calculate a composite key
1. attempt to retrieve a layer with the same key
1. if:
    * found: replace the COPY command with a "fake" one that applies the cached layer instead
    * not found: stop the caching process, keep the COPY command as-is.
      * later after it's executed, upload the new cached layer to the registry with the new key for future builds

do something like:

1. calculate a composite key
1. check if a remote layer with the same key exists - but do not retrieve it
1. if:
    * found: keep the COPY command as-is, _don't_ stop the caching process
    * not found: keep the COPY command as-is, _stop_ the caching process
      * later after it's executed, upload the an _empty_ layer to the registry with the new key for future builds

This way the local context is always used as a source for COPY commands, but would also be used to determine whether the existing cache for subsequent layers can be used or not.

**Comment by isker** [comment]
@tejal29 I will try to produce a PR for this.  It looks to me that we could achieve all of the things you listed just by deleting [the code that makes COPYs cacheable](https://github.com/GoogleContainerTools/kaniko/blob/f20f495051627b988c7449e9b163a4f9f30cc044/pkg/commands/copy.go#L164-L227).

Like @kamaln7 said, we already calculate the composite cache key for non-cacheable COPYs:
https://github.com/GoogleContainerTools/kaniko/blob/f20f495051627b988c7449e9b163a4f9f30cc044/pkg/executor/build.go#L186-L187

This makes me wonder why COPYs were cacheable in the first place 🤔 .

**Comment by kamaln7** [comment]
Amazing, thanks @isker & @tejal29!
