### ISSUE TITLE
kaniko plugin for kubectl

### ISSUE THREAD

**Issue by kvaps** [GoogleContainerTools/kaniko#1403]
Hi I was inspired by https://github.com/GoogleContainerTools/kaniko/pull/1289 and created kaniko plugin for kubectl:
https://github.com/kvaps/kubectl-kaniko

I would like to share it with the community using krew (package manager for kubectl), but I need your approve of using kaniko name for this plugin in krew-index repository, please see https://github.com/kubernetes-sigs/krew-index/pull/785#pullrequestreview-478061023

Let's cooperate :)

**Comment by corneliusweig** [comment]
If the `kaniko` team thinks this plugin fits well to the project, one could also think about hosting its source code in the kaniko repo instead of a standalone project.
@kvaps would you be open to merge your work in here?

---

My line of thought is basically this: @kvaps's plugin is a convenience wrapper around running the kaniko executor in the cluster. So it does make sense to make the connection to the `kaniko` project. However, if it uses the name of the project, it should not be a standalone repo, but be also part of the official repository.

**Comment by kvaps** [comment]
> @kvaps would you be open to merge your work in here?

Sure I can, but I'm not sure if kaniko maintainers would like to mix up two languages (shell and go) in the single project repo.

**Comment by kvaps** [comment]
Btw, I decided to rename **kubectl-kaniko** to **kubectl-build** and place it in my own krew-index repository.

**kubectl build** is better name because it do not conflicts with kaniko, and reflects exact usage, it also correlates with **docker build**:

```console
$ ls
Dockerfile
$ kubectl build -c . -d kvpas/myimage
```

If you like this plugin, new you can install using my own krew-index repository:

```
kubectl krew index add kvaps https://github.com/kvaps/krew-index
kubectl krew install kvaps/build
```

or standard way using curl, described on plugin page:
https://github.com/kvaps/kubectl-build
