### ISSUE TITLE
POWER & Z architecture support

### ISSUE THREAD

**Issue by bahetiamit** [GoogleContainerTools/kaniko#1462]
We are working on adding POWER (ppc64le) and Z (s390x) architecture support for https://github.com/tektoncd/pipeline. Pipeline uses kaniko and I would like to know if kaniko is willing to add similar support.

**Comment by mattmoor** [comment]
Something else to consider here would be to use the qemu-based buildx support to build/publish the kaniko Dockerfiles, and dropping the Bazel stuff I added.

Travis supports s390x and Power, so we could do more testing that way.

I went the Bazel route because it was familiar from the work in distroless, and hadn't messed with the buildx QEMU support, but have now and it's neat.  AFAIK Bazel is the main limiting factor here, so I'd be happy to see it go if we can move the needle on multi-arch.

**Comment by katheris** [comment]
Hi, great to see multi-arch support. Am I right in thinking that Z (s390x) support has not been added to Kaniko yet?
