### ISSUE TITLE
Issues with faccessat2 when building container image

### ISSUE THREAD

**Issue by jkohnert** [GoogleContainerTools/kaniko#1573]
Hey there,

I'm trying to build a container from the archlinix/base image an run into an issue not having access to a file which exists in the build context and is accessible (f.e via cat $file) for the user. Trying to break down the issue by stracing the process a stumbled accross a problem probably introduced by a change in glibc:

```text
...
faccessat2(AT_FDCWD, "/etc/makepkg.conf", R_OK, AT_EACCESS) = -1 EPERM (Operation not permitted)
...
```
According to the documentation [0] faccessat2() *never* returns EPERM, so this must be introduced somewhere else. There are bug reports in redhat [1], [2], and also a patch for docker/seccomp, I assume there is a similar issue here, since kaniko uses non-root privileges, and I am able to build the image [4] using docker.

The error accurs in Line 14 of the Dockerfile, makepkg does not find /etc/makepkg.conf, the error above is from stracing the process while trying to build the image.

I'm not sure what more information to provide at the moment.

[0] https://man7.org/linux/man-pages/man2/faccessat.2.html
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1869030
[2] https://bugzilla.redhat.com/show_bug.cgi?id=1900021
[3] https://github.com/moby/moby/pull/41353/files
[4] https://github.com/imrehg/archlinux-makepkg-docker/blob/master/Dockerfile

**Comment by jhuntwork** [comment]
I'm not using kaniko, but I stumbled across this description as it exactly matches my issue on a similar system using just docker. I've seen this behavior in both docker 20.10.2 and 20.10.3 and the issue arises with any system call using faccessat2. It can be bypassed using `docker run --privileged` or using `docker run --security-opt seccomp=unconfined`, but interestingly it still fails when explicitly using docker's default seccomp policy that notably allows faccessat2, here: https://github.com/moby/moby/blob/master/profiles/seccomp/default.json

If it's happening in kaniko too I wonder if the issue lies with a common go package.

**Comment by jhuntwork** [comment]
Lots of related threads/issues around this, hard to pick just one, but this might be helpful: https://github.com/moby/moby/issues/41704 Basically it looks like even though docker itself has added in the requirements to support it, its releases (and its runc component in particular) are still being built using an older version of libseccomp which do not yet handle the syscalls appropriately.

**Comment by aaron-prindle** [comment]
Going to close this issue - the linked moby issue https://github.com/moby/moby/issues/41704 seems resolved as of March 2021.  In attempting to build the Dockerfile here https://github.com/imrehg/archlinux-makepkg-docker/blob/master/Dockerfile I got a successful build (not sure if I am missing something from the description though)

If someone in the thread here as additional concerns or information feel free to comment and I can re-open the issue.
