### ISSUE TITLE
registry-mirror setting in /kaniko/.docker/config.json

### ISSUE THREAD

**Issue by oweis-telit** [GoogleContainerTools/kaniko#1752]
it would be very nice to have the [registry-mirror](https://github.com/GoogleContainerTools/kaniko#--registry-mirror)  functionality also available in the `/kaniko/.docker/config.json` file.

as we can provide the config for each runner in this file, the users would not have to use the parameter manually in each of their pipelines.

as I searched for it and couldn't find it, is there any central documentation which settings are possible in the `/kaniko/.docker/config.json` file?

thanks in advance
Oliver

**Comment by chris-ng-scmp** [comment]
I am looking for this feature as well

**Comment by imjasonh** [comment]
The `.docker/config.json` used by Kaniko is the same as the one used by Docker, mainly used to describe auth options. For example, when you `docker login`, `config.json` is updated to store those credentials.

I'd prefer not to add Kaniko-specific options to the config, since it presents an opportunity for the two configs to diverge over time.

Perhaps Kaniko supporting an env var to describe mirror registries would help in your case? I think that might even be something Cobra/Viper already support, it'd just need to be tested and documented.

**Comment by chris-ng-scmp** [comment]
> The `.docker/config.json` used by Kaniko is the same as the one used by Docker, mainly used to describe auth options. For example, when you `docker login`, `config.json` is updated to store those credentials.
> 
> I'd prefer not to add Kaniko-specific options to the config, since it presents an opportunity for the two configs to diverge over time.
> 
> Perhaps Kaniko supporting an env var to describe mirror registries would help in your case? I think that might even be something Cobra/Viper already support, it'd just need to be tested and documented.

Agree, anyway to not set the mirror registries by flag is good to solve my use case

My use case is developers use different flag options with Kaniko, they override the script in CI, we can't make sure all the jobs set by different developers in different projects with a proper registry-mirror flag.
