### ISSUE TITLE
Extending vs copying from Kaniko image?

### ISSUE THREAD

**Issue by ferbs** [GoogleContainerTools/kaniko#1868]
I'd like to use Kaniko in a microservice that builds containers based on data collected during runtime. It's not for CI/CD but shares characteristics.

I'm reluctant to try copying the kaniko binary into my service's Containerfile/Dockerfile  using `COPY --from` because the docs say:
> kaniko is meant to be run as an image: gcr.io/kaniko-project/executor.

Extending Kaniko's image using `FROM gcr.io/kaniko-project/executor:v1.7.0-debug` doesn't seem like a promising approach either though, since it's based on a too-slender busybox base. 

Ideally, I'd like my service to run kaniko within debian:bullseye-slim and AWS Lambda. 

What do you suggest?

**Comment by imjasonh** [comment]
I do something like this in https://kaniko.kontain.me, effectively using the `FROM kaniko` approach you describe. It's, meh, fine. I'd go with that over copying the binary from the image, but either is effectively the same.

**Comment by ferbs** [comment]
So one option is something like kontain.me (cool example) plus building in their [Lambda Runtime](https://github.com/aws/aws-lambda-runtime-interface-emulator).  But if copying is doable too, I'd guess less agony, especially for non-Go flavors.

Is there anything outside of /kaniko that would require copying?

**Comment by imjasonh** [comment]
I see, having to include the Lambda Runtime probably rules out `FROM kaniko` in your case. In that case `COPY`ing it out should work. 

I read the advice that "kaniko is meant to be run as an image" more as a warning against running it as a binary directly in your environment, since it expects to have full access to everything in its container, and may mess stuff up otherwise. If you're running it in Lambda you should be safe from that issue.

Other than that the warning is also saying "don't assume we'll be able to fix/prioritize bugs that only affect your unusual way of using kaniko" but that shouldn't stop you from experimenting.

You should really only need to copy out `/kaniko/executor` AFAIK, the rest of `/kaniko` is cred helpers and SSL certs, which you can either get by without or otherwise get from your debian base.

**Comment by ferbs** [comment]
Kaniko runs in a `node:14.18-bullseye-slim` base image but not `public.ecr.aws/lambda/nodejs:14`. I'll post details in a separate ticket. 

Even though I could get it to run by adding the Lambda Runtime to the Debian base, v1.7.0 won't work in Lambda because of #1869.

**Comment by imjasonh** [comment]
Marking this as closed, #1869 seems like the next blocker.
