### ISSUE TITLE
Error building image with customPlatform

### ISSUE THREAD

**Issue by errrken** [GoogleContainerTools/kaniko#2024]
Hi,

Trying to build an arm64 image from a amd64 host, based on a python:3.9.10 Dockerfile.

` /kaniko/executor --customPlatform=linux/arm64 --context $PROJECT_DIR --dockerfile $PROJECT_DIR/Dockerfile --destination $DEST`

The output I get is:

```
...

INFO[0014] RUN apt-get update && apt-get install -y     netcat     xmlsec1     libpango-1.0-0     && rm -rf /var/lib/apt/lists/* 

INFO[0014] Taking snapshot of full filesystem...        

INFO[0019] cmd: /bin/sh                                 

INFO[0019] args: [-c apt-get update && apt-get install -y     netcat     xmlsec1     libpango-1.0-0     && rm -rf /var/lib/apt/lists/*] 

INFO[0019] Running: [/bin/sh -c apt-get update && apt-get install -y     netcat     xmlsec1     libpango-1.0-0     && rm -rf /var/lib/apt/lists/*] 

error building image: error building stage: failed to execute command: starting command: fork/exec /bin/sh: exec format error
Cleaning up file based variables

ERROR: Job failed: exit code 1
```

Any ideas why?

Thanks

**Comment by imjasonh** [comment]
This is not feasible using Kaniko, because Kaniko assumes and requires that the host architecture matches the architecture of the image being built.

You will probably want to use `docker buildx` to accomplish this:
- https://medium.com/@artur.klauser/building-multi-architecture-docker-images-with-buildx-27d80f7e2408
- https://medium.com/@tonistiigi/faster-multi-platform-builds-dockerfile-cross-compilation-guide-part-1-ec087c719eaf
