### ISSUE TITLE
Image build slower than docker in docker

### ISSUE THREAD

**Issue by kunmingg** [GoogleContainerTools/kaniko#220]
Env: GKE 1.8
Hi,
Our pipeline need to build docker image within k8s, and think kaniko would be great tool for that.
During test we found kaniko takes more time to build images compared to docker in docker solution, which could be a pain when image update frequency matters.
Is it expected or caused by something I didn't config correctly?

Thanks

**Comment by priyawadhwa** [comment]
Hey @kunmingg, so right now it is somewhat expected since we haven't implemented caching yet (you can follow that issue here #102). Until then, you could try using the `--snapshotMode=time` flag, which will only look at file mtime when snapshotting (should be a bit faster than the default snapshotter, but I haven't done any benchmarking).

**Comment by r2d4** [comment]
Let's close this and track it in the caching issue https://github.com/GoogleContainerTools/kaniko/issues/102
