### ISSUE TITLE
It is unclear how to use kaniko inside a container

### ISSUE THREAD

**Issue by slonopotamus** [GoogleContainerTools/kaniko#2213]
README says

> kaniko is a tool to build container images from a Dockerfile, **inside a container** or Kubernetes cluster.

then it says

> kaniko is meant to be **run as an image**: gcr.io/kaniko-project/executor

The question is: how user is supposed to run an image when they are inside a container?

**Actual behavior**
Docs insist that user is should only run kaniko using gcr.io/kaniko-project/executor image:

> We do not recommend running the kaniko executor binary in another image, as it might not work

**Expected behavior**
A clear and concise docs on how to run kaniko when inside the container.

**To Reproduce**
1. Enter any Docker container, for example, `docker run --rm -it ubuntu`
2. Attempt to follow kaniko instructions to use it

 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by slonopotamus** [comment]
I mean, if I can run an image (== I can execute `docker run gcr.io/kaniko-project/executor`), then I can just `docker build` and I don't need kaniko. And if I cannot use `docker run` (== I am inside an unpriviledged container or I am on a host without Docker at all), I just cannot run kaniko image.

**Comment by ngoyal16** [comment]
@slonopotamus you can use containerd instead of docker to run it and then use the kaniko to build the docker image. 

for example docker runtime was depcreated in kubernetes and from v1.24 containerd will be the only option to run the container images. and containerd cannot build the container images in that case you can use the kaniko to build the container image.

if you have access to docker or DIND option it is a good choice to use that apart from the security risk. but if you don't have docker but other container runtime in that case you have to use tools kaniko, buildah, etc. to build the images.

**Comment by slonopotamus** [comment]
> you can use containerd instead of docker to run it and then use the kaniko to build the docker image.

Makes sense.
