### ISSUE TITLE
any new release?

### ISSUE THREAD

**Issue by tooptoop4** [GoogleContainerTools/kaniko#2405]
getting roasted on CVEs in the debug image

**Comment by kfix** [comment]
guessing this is a reference to the ones in #2276 ?

**Comment by charlie-ang-collibra** [comment]
Ditto!  Also interested in planned next release.  🙏

**Comment by remissio** [comment]
we are waiting for [this](https://github.com/GoogleContainerTools/kaniko/pull/2269) to be in a release

**Comment by alewis001** [comment]
It seems awfully quiet on the new issues that have been raised since the latest release in Sept 2022. That's not a criticism, just trying to make a decision on whether to use Kaniko or not.

**Comment by mballoni** [comment]
@alewis001 what other rootless/daemonless options are you looking at ?
I'm happy with Kaniko but would feel safer with good options at hand as well.

**Comment by alewis001** [comment]
I think there are various options with root and rootless podman but that's only part of the solution.

In an honesty, I was hoping that Kaniko was active and it was a no brainer decision and I didn't have to think much about other options. That may even be the case and the fact that nothing has happened in Kaniko for a while now is purely a sign of its maturity. It's just that the issues raised would somewhat suggest that there are things that need to happen and 6 months seems like a long time for nothing to happen. Of course, the project may just be waiting for people to submit PRs rather than waiting for Google employees.
