### ISSUE TITLE
Kaniko creates more layers than Docker

### ISSUE THREAD

**Issue by lubo** [GoogleContainerTools/kaniko#313]
When using `VOLUME` Dockerfile instruction, Kaniko creates a new layer, which contains only the directories specified in `VOLUME` instruction. Docker does not create those directories in the image at all.

**Comment by peter-evans** [comment]
This issue was interesting to me so I had a quick look at Kaniko's code and it looks like a snapshot of the file system is taken with each layer it builds. If the snapshot contains data it adds a layer. The `VOLUME` command is creating directories and so the layer has "content."

If Docker doesn't add a layer with the `VOLUME` command, where does that info get stored in the final container image? Presumably it's written the image somewhere and the directories are created when the container starts.
