### ISSUE TITLE
Feature: Add automatic updates to Kaniko

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/kaniko#335]
Currently users have to manually check whether a new update of Kaniko is available. It would be great if Kaniko could automatically check if a new update was available and prompt a user.

**Comment by pvdissel** [comment]
When implementing this, please keep in mind:
- it should not be blocking if the update site cannot be reached
- it should not force you to update directly

This because, like us, we (try to) run kaniko as container inside GCP, with the internet closed off.
So I would prefer, if this is going to be implemented;
- that the user should add a flag indicating they want to be notified if there is a newer version, eg. `--check-for-updates`, which should only show a message in the output and continue its normal tasks
- if in-place update is part of the implementation, that the user should add a flag indicating they want to update in-place, eg. `--update`

**Comment by bobcatfish** [comment]
Gonna close this for now, this was part of an effort our team was making to create an update lib which seems like not the direction we're currently going atm.
