### ISSUE TITLE
signatures support？

### ISSUE THREAD

**Issue by phantooom** [GoogleContainerTools/kaniko#749]
i want use kaniko. is it support  digital signatures?

ref: https://docs.docker.com/engine/security/trust/content_trust/

**Comment by tejal29** [comment]
no not yet. We will definitely look in to it.

**Comment by dani29** [comment]
Hi @phantooom, sorry for late response, but we wanted to clarify the issue.
Is your request is to provide a signed Kaniko image, so that you could run enforce its' signature when you run it in your cluster, or to enable signing images built using Kaniko?

If it's the latter, I believe it's out of scope of Kaniko. I'd recommend taking a look at [Kritis,](https://github.com/grafeas/kritis) an open-source tool that allows you accomplishing this. There's an [example](https://github.com/grafeas/kritis/blob/master/docs/signer_install.md) of a GCP based set-up, where you could run Kaniko as a GCB step and then signed the produced image using Kritis.

**Comment by tejal29** [comment]
Closed as won't fix since GCP already supports this

**Comment by osman** [comment]
@dani29 @tejal29 I have the same request. It's actually in two parts and I use AWS so the original answer cannot be adapted for my case since it is very GCP specific.

The first part is to be able to pull only signed images and validate it against a notary server when content trust is enabled and the second part is to sign a built image using a notary server before pushing.

**Comment by dani29** [comment]
Hi @osman! We'll be happy to look into implementing it, but firstly we need to better understand the requirement and see if it's within the scope of Kaniko, or actually should be performed by another tool.

Could you please share how this workflow is currently working for you with Docker, i.e what commands are you running?
Is your feature request is basically integrating with [Notary](https://github.com/theupdateframework/notary), in a similar way `docker trust` does?

**Comment by kyrogue** [comment]
@dani29 yes, most workflows tutorials are catered towards Docker as the container engine, if we are using Kaniko how would the simple workflow with notary work?

**Comment by kfox1111** [comment]
+1 to notery support. I'd like to sign images I've built with kaniko and run them in a kubernetes that validates signatures.  https://github.com/IBM/portieris/ looks like a good way to enforce it. It doesn't require docker to operate.

**Comment by nayan-kalita** [comment]
can someone update this. we need to sign images build with kaniko to establish content trust. same way how docker build does with DOCKER_CONTENT_TRUST=1

**Comment by akash2237778** [comment]
+1 for signature support. We are using kaniko as a very important and integral part of our project [pubgrade](https://github.com/elixir-cloud-aai/pubgrade). And we need to build trust for the images build by kaniko as service is decoupled and need trust for the images pulled at the deployment's end. 
If it is feasible to implement DCT (https://docs.docker.com/engine/security/trust/) at kaniko we'll love to do that. If yes? could you please provide some docs to begin with?

@tejal29 @dani29

**Comment by kfox1111** [comment]
Another option that seems to be gaining traction is this:
https://github.com/sigstore/cosign
