### ISSUE TITLE
Multi Stage build not respecting dependency tree

### ISSUE THREAD

**Issue by duxbuse** [GoogleContainerTools/kaniko#815]
**Actual behavior**
Kaniko builds all stages of a multi stage then only returns the stage specified in the `--target` declaration.

**Expected behavior**
Kaniko should only build the stages that the `--target` has as dependencies.

**To Reproduce**
Multi stage file like this:
```yaml
FROM alpine AS builder
  COPY ./shared-content .
  RUN make build

FROM builder AS tester
  COPY testingPackage .
  RUN make test

FROM builder AS deployable
  COPY --from builder application.bin application.bin
```

I would expect that when building this file with `--target` = `deployable` that the test layers would not be built. Partly because they are not used so they will just be thrown away.
Current versions of docker do this dependency mapping to only build required steps.
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [x] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [x] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [x] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [x] </li></ul>|

**Comment by Akkarine** [comment]
Same here. I would also add, that if there is no dependencies at all, kaniko will build all unwanted stages  in order they are declared in Dockerfile till it comes to target. Luckly, if target is the first stage, other stages not initiated :)

**Comment by donmccasland** [comment]
Pardon my ignorance, is there a corollary functionality in docker build?

**Comment by Akkarine** [comment]
> Pardon my ignorance, is there a corollary functionality in docker build?

I didn't understood question. Are you asking, is there is any benefits from using multi-stage Dockerfile?

**Comment by cvgw** [comment]
This may be the same issue as #775

**Comment by Akkarine** [comment]
> Pardon my ignorance, is there a corollary functionality in docker build?

If you use DOCKER_BUILDKIT=1, dependencies resolved correctly.

**Comment by frickenate** [comment]
Yep, being burned by this. Migrating to GitLab CI with existing multi-stage builds which were using eg. `DOCKER_BUILDKIT=1 docker build --target release` with the previous build system. Looking at kaniko rather than docker-in-docker, but no support for dependency resolution in multi-stage builds is a killer that has us traveling back in time to having to build Dockerfiles dynamically? Heck no.

**Comment by frickenate** [comment]
Hot damn, this was the only known blocker for my team at work (using GitLab CI) to use kaniko instead of docker-in-docker. I’m a little blind with the PR in terms of implementation. Can you please explain:

1. Which version of kaniko this feature is available in;

2. What the default behaviour in that version is, and how exactly to override the default if necessary? The PR went back and forth on flag names, and not sure exactly how to modify the default if necessary to enable dependency detection (particularly when using GitLab CI)?

Thank you so much.
