### ISSUE TITLE
Add support for --chown flag to COPY command

### ISSUE THREAD

**Issue by priyawadhwa** [GoogleContainerTools/kaniko#9]
See #1 for details

**Comment by TheOriginalAlex** [comment]
I'm a noob contributor, but would like to help make this happen!

**Comment by pmcq** [comment]
Hi I'm interested in getting this issue resolved for multi-stage builds we are working on, but don't have experience contributing to a go repo.  I'd like to help out if possible though (at least for some of the `--chown` syntax)

**Comment by priyawadhwa** [comment]
Hey @pmcq , thanks for your interest. I've outlined a few steps you might want to take to add this feature

1. In [copy.go](https://github.com/GoogleContainerTools/kaniko/blob/master/pkg/commands/copy.go), in `Execute`, you'll first want to get uid/gid from `c.cmd.Chown`, which is a string. We do something similar for the `USER` command [here](https://github.com/GoogleContainerTools/kaniko/blob/master/pkg/commands/user.go), so you might be able to move some of that logic into a separate function which both `COPY` and `USER` could call.
2. In the copy command we call [util.CopyDir](https://github.com/GoogleContainerTools/kaniko/blob/master/pkg/commands/copy.go#L82) and [util.CopyFile](https://github.com/GoogleContainerTools/kaniko/blob/master/pkg/commands/copy.go#L98). You'll need to change the signatures of these functions [here](https://github.com/GoogleContainerTools/kaniko/blob/master/pkg/util/fs_util.go#L476) and [here](https://github.com/GoogleContainerTools/kaniko/blob/master/pkg/util/fs_util.go#L426) to take in the uid/gid, and apply it to every file that's copied over in those functions.
3. You can run our unit tests by running `make test` (you'll have to update some of them since I think we use `CopyFile` and `CopyDir` in a few different places). 

Let me know if you have any more questions.

**Comment by pmcq** [comment]
I made changes in a fork here: https://github.com/GoogleContainerTools/kaniko/compare/master...pmcq:copy-chown?expand=1 and built an image and used it to run dockerfiles with `COPY --chown` flag succesfully. All existing unit tests pass, however I don't see any existing tests on util.CopyDir/CopyFile or CopySymlink that need modification.  

I was thinking of creating new tests that just copy file/dir/symlink but since the user running the testcases isn't going to be a root user, it wouldn't be allowed to chown the file to someone else, so the testcase wouldn't add anything specific checks for this change.  Should I open a PR or is there a different type of testing you would like?

**Comment by priyawadhwa** [comment]
@pmcq thanks for opening a PR!

**Comment by swistaczek** [comment]
Hey, this is still an active issue. PR https://github.com/GoogleContainerTools/kaniko/pull/250 is closed and abandoned.

**Comment by ataillefer** [comment]
Hi, any news on this?

It's really problematic when using multi-stage to not be able to use `COPY` and change the owner of the copied directory.

Of course, a workaround is to call an extra `RUN chown -R uid:gid mydir` after the `COPY` instruction, but it adds a layer of the size of the copied directory, so directly impacts the final image size...

Thanks

**Comment by wstrange** [comment]
Any updates on this issue?

**Comment by diclophis** [comment]
I just ran into this bug as well...
